don't fail for on attempt to install scm
This patch fixes following behaviour:
```
➜  tarantoolctl rocks install errors
Installing http://rocks.tarantool.org/errors-scm-1.rockspec

Cloning into 'errors'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 225 (delta 11), reused 16 (delta 7), pack-reused 195
Receiving objects: 100% (225/225), 51.48 KiB | 1.35 MiB/s, done.
Resolving deltas: 100% (116/116), done.
-- Could NOT find LDOC (missing: LDOC)
-- Configuring done
-- Generating done
-- Build files have been written to: /private/var/folders/5k/pq85j1617xn_kbndt1rhlwlr0000gp/T/luarocks_errors-scm-1-7908081/errors/build.luarocks
Install the project...
-- Install configuration: ""
-- Installing: errors/.rocks/share/tarantool/rocks/errors/scm-1/lua/errors
-- Installing: errors/.rocks/share/tarantool/rocks/errors/scm-1/lua/errors/deprecate.lua
-- Installing: errors/.rocks/share/tarantool/rocks/errors/scm-1/lua/errors.lua

Error: Directory 'doc' not found
```

This happend because ldoc is missing. However it seems we should
simply skip such cases and allow to install scm version.

Closes #21